### ISSUE TITLE
Arch package

### ISSUE THREAD

**Issue by fauno** [deksai/pam_abl#2]
Made an AUR package :)

https://aur.archlinux.org/packages/pam_abl-git/

**Comment by fauno** [comment]
I was able to run tests though it wasn't clear at all (`./pam_abl_test` tells me to pass a db module, `./pam_abl_test -h` to check help runs tests but it fails 13, I had to read the code to understand what was it expecting).

Anyway, all tests passed, building with:

* kyotocabinet 1.2.77
* db 5.3.28
* pam 1.3.1
* cunit 2.1.3

**Comment by deksai** [comment]
Many apologies, I apparently lost some alias on my mail server, and never saw this!   This is great, thank you!
